# Stage environment values - matches existing deployment
# DO NOT change these values - they match the current working deployment

replicaCount: 1

image:
  repository: ghcr.io/durantic/controlplane
  tag: main
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

django:
  debug: true
  allowedHosts: "api.stage.durantic.dev,controlplane-durantic,controlplane-durantic.default.svc.cluster.local"
  controlPlaneHost: "api.stage.durantic.dev"
  csrfTrustedOrigins: "https://api.stage.durantic.dev"

  database:
    host: "postgresql-cluster-rw"
    port: 5432
    name: "app"
    user: "app"
    existingSecret: "postgresql-cluster-app"
    secretKeys:
      password: "password"

  redis:
    host: "redis-standalone"
    port: 6379
    password: ""
    existingSecret: ""

  s3:
    endpointUrl: "http://minio-instance:9000"
    region: "us-east-1"
    ipxeBucket: "ipxe-builds"
    osImagesBucket: "os-images"
    useSSL: false
    verify: false
    addressingStyle: "path"
    existingSecret: "minio-instance"
    accessKeyId: ""
    secretAccessKey: ""

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: api.stage.durantic.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: controlplane-stage-tls
      hosts:
        - api.stage.durantic.dev

# Disable subcharts - use existing cluster resources
postgresql:
  enabled: false

redis:
  enabled: false

minio:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: false

persistence:
  enabled: false

# Health probes - use /admin/ endpoint
livenessProbe:
  httpGet:
    path: /admin/
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /admin/
    port: http
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3
