# Stage environment values for controlplane
# Based on values-dev.yaml but for staging environment

replicaCount: 2

image:
  repository: ghcr.io/durantic/controlplane
  tag: main
  pullPolicy: Always

django:
  debug: false
  allowedHosts: "api.stage.durantic.dev,controlplane-durantic,controlplane-durantic.default.svc.cluster.local"

  # Database configuration - using existing cluster resources
  database:
    host: "postgresql-cluster-rw.default.svc.cluster.local"
    port: "5432"
    name: "durantic"
    user: "durantic"
    # password: set via secret

  # Redis configuration - using existing cluster resources
  redis:
    host: "redis-master.default.svc.cluster.local"
    port: "6379"
    # password: set via secret

  # S3/MinIO configuration
  s3:
    endpointUrl: "http://minio.default.svc.cluster.local:9000"
    region: "us-east-1"
    ipxeBucket: "ipxe-builds"
    osImagesBucket: "os-images"
    useSSL: false
    verify: false
    addressingStyle: "path"

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
  hosts:
    - host: api.stage.durantic.dev
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: controlplane-stage-tls
      hosts:
        - api.stage.durantic.dev

# Disable subcharts in staging - use existing cluster resources
postgresql:
  enabled: false

redis:
  enabled: false

minio:
  enabled: false

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 2Gi

autoscaling:
  enabled: false

persistence:
  enabled: false
